// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6XHv-mtB1u4dlKPQsXT7DI33gVYkQA1w',
    appId: '1:288159795041:web:772939af79b018a130e720',
    messagingSenderId: '288159795041',
    projectId: 'budgetbuddy-45754',
    authDomain: 'budgetbuddy-45754.firebaseapp.com',
    storageBucket: 'budgetbuddy-45754.appspot.com',
    measurementId: 'G-6PR75HJT58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3gIax8ngAZvnKy0AUnp6oSENlg5oWpQ0',
    appId: '1:288159795041:android:f7d7d8af68d23ec030e720',
    messagingSenderId: '288159795041',
    projectId: 'budgetbuddy-45754',
    storageBucket: 'budgetbuddy-45754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFYDGmKSrYC5VygSosAVFgjJu5AqSxD8',
    appId: '1:288159795041:ios:7ec1eb3a9e98f4b730e720',
    messagingSenderId: '288159795041',
    projectId: 'budgetbuddy-45754',
    storageBucket: 'budgetbuddy-45754.appspot.com',
    iosBundleId: 'com.example.budgetbuddy',
  );
}
